STRINGS = {
    'uz': {
        'welcome': "🌆 Xayrli kech! Minecraft modlari uchun avtoposting botiga xush kelibsiz.",
        'select_lang': "Iltimos, tilni tanlang:",
        'main_menu': "🏠 Asosiy menyu",
        'btn_create': "📝 Post yaratish",
        'btn_style': "🎭 Stil tanlovi",
        'btn_channel': "📢 Kanal tanlovi",
        'btn_watermark': "🖼️ Mening vatermarkim",
        'btn_stats': "📈 Mening statistikami",
        'btn_queue': "📊 Navbat holati",
        'btn_tariffs': "💰 Tariflar",
        'btn_admin': "🛡️ Admin paneli",
        'btn_cancel': "❌ Bekor qilish",
        'btn_home': "🏠 Asosiy menyu",
        'btn_webapp': "🌐 Web App",
        'ask_channel': "⚠️ Kanalni ulash kerak. Kanalingizning @username ni yuboring:",
        'done': "✅ Tayyor!",
        'style_desc': "🎭 <b>Stil tanlovi</b>\n\nAI qanday uslubda post yozishini tanlang:",
        'tariffs_desc': "💰 <b>TARIFLAR</b>\n\nRejani tanlang va bot imkoniyatlaridan to'liq foydalaning.",
    },
    'ru': {
        'welcome': "🌆 Добрый вечер! Добро пожаловать в бот для автопостинга Minecraft модов.",
        'select_lang': "Пожалуйста, выберите язык:",
        'main_menu': "🏠 Главное меню",
        'btn_create': "📝 Создать пост",
        'btn_style': "🎭 Выбор стиля",
        'btn_channel': "📢 Выбор канала",
        'btn_watermark': "🖼️ Мой вотермарк",
        'btn_stats': "📈 Моя статистика",
        'btn_queue': "📊 Статус очереди",
        'btn_tariffs': "💰 Тарифы",
        'btn_admin': "🛡️ Админ-панель",
        'btn_cancel': "❌ Отмена",
        'btn_home': "🏠 Главное меню",
        'btn_webapp': "🌐 Web App",
        'ask_channel': "⚠️ Нужно привязать канал. Пришлите @username вашего канала:",
        'done': "✅ Готово!",
        'style_desc': "🎭 <b>Выбор стиля</b>\n\nВыберите, в каком стиле AI будет писать посты:",
        'tariffs_desc': "💰 <b>ТАРИФЫ</b>\n\nВыберите план и используйте бота на полную мощность.",
    },
    'en': {
        'welcome': "🌆 Good evening! Welcome to the Minecraft Mods Autoposting Bot.",
        'select_lang': "Please select a language:",
        'main_menu': "🏠 Main Menu",
        'btn_create': "📝 Create Post",
        'btn_style': "🎭 Choose Style",
        'btn_channel': "📢 Choose Channel",
        'btn_watermark': "🖼️ My Watermark",
        'btn_stats': "📈 My Statistics",
        'btn_queue': "📊 Queue Status",
        'btn_tariffs': "💰 Tariffs",
        'btn_admin': "🛡️ Admin Panel",
        'btn_cancel': "❌ Cancel",
        'btn_home': "🏠 Main Menu",
        'btn_webapp': "🌐 Web App",
        'ask_channel': "⚠️ You need to link a channel. Send your channel's @username:",
        'done': "✅ Done!",
        'style_desc': "🎭 <b>Style Selection</b>\n\nChoose the style in which AI will write posts:",
        'tariffs_desc': "💰 <b>TARIFFS</b>\n\nChoose a plan and use the bot to its full potential.",
    }
}

def t(key, lang='uz'):
    return STRINGS.get(lang, STRINGS['uz']).get(key, key)
